
--
-- TABLE: CRUD_PESSOA
--

CREATE TABLE CRUD_PESSOA(
    ID_PESSOA               		NUMBER(9, 0)    NOT NULL,
    NOME_PESSOA						VARCHAR2(255)	NOT NULL,
    GENERO_PESSOA					VARCHAR2(255)	NOT NULL,
    CONSTRAINT PK_PESSOA PRIMARY KEY (ID_PESSOA)
)
;

--
-- SEQUENCE: SEQ_CRUD_PESSOA
--

CREATE SEQUENCE SEQ_CRUD_PESSOA
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
    NOCACHE
--  NOORDER
;

--
-- TABLE: CRUD_DOCUMENTO
--
--
CREATE TABLE CRUD_DOCUMENTO(
    ID_DOCUMENTO                   	NUMBER(9, 0)	NOT NULL,
    TIPO_DOCUMENTO	    		    VARCHAR2(25)	NOT NULL,
    VALOR_DOCUMENTO	            	VARCHAR2(25)    NOT NULL,
    ID_PESSOA                   	NUMBER(9, 0)    NOT NULL,
    CONSTRAINT PK_DOCUMENTO PRIMARY KEY (ID_DOCUMENTO)
)
;

--
-- SEQUENCE: SEQ_CRUD_DOCUMENTO
--
--
CREATE SEQUENCE SEQ_CRUD_DOCUMENTO
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
  	NOCACHE
--  NOORDER
;

--
-- TABLE: CRUD_TIPO_DOCUMENTO
--

CREATE TABLE CRUD_TIPO_DOCUMENTO(
    ID_TIPO_DOCUMENTO          		NUMBER(9, 0)    NOT NULL,
    CHAVE_TIPO_DOCUMENTO			VARCHAR2(255)	NOT NULL,
    VALOR_TIPO_DOCUMENTO			VARCHAR2(255)	NOT NULL,
    CONSTRAINT PK_TIPO_DOCUMENTO PRIMARY KEY (ID_TIPO_DOCUMENTO)
)
;

--
-- SEQUENCE: SEQ_CRUD_TIPO_DOCUMENTO
--

CREATE SEQUENCE SEQ_CRUD_TIPO_DOCUMENTO
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
    NOCACHE
--  NOORDER
;
