
--
-- TABLE: CRUD_PESSOA
--

CREATE TABLE CRUD_PESSOA(
    ID_PESSOA               		NUMBER(9, 0)    NOT NULL,
    NOME_PESSOA						VARCHAR2(255)	NOT NULL,
    GENERO_PESSOA					VARCHAR2(255)	NOT NULL,
    CONSTRAINT PK_PESSOA PRIMARY KEY (ID_PESSOA)
)
;

--
-- SEQUENCE: SEQ_CRUD_PESSOA
--

CREATE SEQUENCE SEQ_CRUD_PESSOA
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
    NOCACHE
--  NOORDER
;

--
-- TABLE: CRUD_DOCUMENTO
--
--
CREATE TABLE CRUD_DOCUMENTO(
    ID_DOCUMENTO                   	NUMBER(9, 0)	NOT NULL,
    VALOR_DOCUMENTO	            	VARCHAR2(25)    NOT NULL,
    ID_PESSOA                   	NUMBER(9, 0)    NOT NULL,
    ID_TIPO_DOCUMENTO	    	    NUMBER(9, 0)    NOT NULL,
    CONSTRAINT PK_DOCUMENTO PRIMARY KEY (ID_DOCUMENTO)
)
;

--
-- SEQUENCE: SEQ_CRUD_DOCUMENTO
--
--
CREATE SEQUENCE SEQ_CRUD_DOCUMENTO
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
  	NOCACHE
--  NOORDER
;

--
-- TABLE: CRUD_TIPO_DOCUMENTO
--

CREATE TABLE CRUD_TIPO_DOCUMENTO(
    ID_TIPO_DOCUMENTO          		NUMBER(9, 0)    NOT NULL,
    CHAVE_TIPO_DOCUMENTO			VARCHAR2(255)	NOT NULL,
    VALOR_TIPO_DOCUMENTO			VARCHAR2(255)	NOT NULL,
    CONSTRAINT PK_TIPO_DOCUMENTO PRIMARY KEY (ID_TIPO_DOCUMENTO)
)
;

--
-- SEQUENCE: SEQ_CRUD_TIPO_DOCUMENTO
--

CREATE SEQUENCE SEQ_CRUD_TIPO_DOCUMENTO
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
    NOCACHE
--  NOORDER
;

--
-- TABLE: CRUD_ENDERECO
--

CREATE TABLE CRUD_ENDERECO(
    ID_ENDERECO  	        		NUMBER(9, 0)    NOT NULL,
    CEP_ENDERECO					VARCHAR2(255)	NOT NULL,
    CIDADE_ENDERECO					VARCHAR2(255)	NOT NULL,
    COMPLEMENTO_ENDERECO			VARCHAR2(255)	,
    ESTADO_ENDERECO					VARCHAR2(255)	NOT NULL,
    LOGRADOURO_ENDERECO				VARCHAR2(255)	NOT NULL,
    NUMERO_ENDERECO					VARCHAR2(255)	NOT NULL,
    CONSTRAINT PK_ENDERECO PRIMARY KEY (ID_ENDERECO)
)
;

--
-- SEQUENCE: SEQ_CRUD_ENDERECO
--

CREATE SEQUENCE SEQ_CRUD_ENDERECO
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
    NOCACHE
--  NOORDER
;

--
-- TABLE: CRUD_PESSOA_ENDERECO
--

CREATE TABLE CRUD_PESSOA_ENDERECO(
    ID_ENDERECO  	        		NUMBER(9, 0)    NOT NULL,
    ID_PESSOA	  	        		NUMBER(9, 0)    NOT NULL
)
;

--
-- TABLE: CRUD_CONTATO
--

CREATE TABLE CRUD_CONTATO(
    ID_CONTATO  	        	NUMBER(9, 0)    NOT NULL,
    ID_PESSOA  	        	    NUMBER(9, 0)    NOT NULL,
    ID_TIPO_CONTATO        	    NUMBER(9, 0)    NOT NULL,
    VALOR_CONTATO				VARCHAR2(255)	NOT NULL,
    IS_PRINCIPAL_CONTATO        BOOLEAN NOT NULL,
    CONSTRAINT PK_CONTATO PRIMARY KEY (ID_CONTATO)
)
;

--
-- SEQUENCE: SEQ_CRUD_CONTATO
--

CREATE SEQUENCE SEQ_CRUD_CONTATO
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
    NOCACHE
--  NOORDER
;